In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
W = torch.rand(6)
x = torch.tensor([10,10,10,10,10,10])
b= torch.tensor(3)

In [3]:
W

tensor([0.1992, 0.0884, 0.4974, 0.1643, 0.3293, 0.9779])

In [4]:
y = W*x + b

In [5]:
y

tensor([ 4.9919,  3.8839,  7.9741,  4.6431,  6.2932, 12.7791])

In [6]:
W*x

tensor([1.9919, 0.8839, 4.9741, 1.6431, 3.2932, 9.7791])

In [7]:
import hiddenlayer as hl
#user to visualize hidden layer

In [16]:
x_train = np.array([[1],[2],[5],[7], [10]], dtype = np.float32)
y_train = np.array([[10],[25],[55],[75], [100]], dtype = np.float32)

In [17]:
X_train =  torch.tensor(x_train)
Y_train =  torch.tensor(y_train)

In [18]:
x_train.shape

(5, 1)

In [19]:
X_train.shape

torch.Size([5, 1])

In [20]:
ip = 1
op = 1
hid = 100

In [21]:
model1 = torch.nn.Sequential(torch.nn.Linear(ip, hid),
                            torch.nn.Linear(hid, op))

In [25]:
#hl.build_graph(model1, X_train)

In [29]:
model2 = torch.nn.Sequential(torch.nn.Linear(ip, hid),
                            torch.nn.Linear(hid, op),
                            torch.nn.Sigmoid(),
                            torch.nn.Linear(hid, op))

In [32]:
#hl.build_graph(model2, torch.zeros([1]))